--------------------------------------------------------------------------------
-- Task 3 - Invoices
-- Database structures
--------------------------------------------------------------------------------


--------------------------------------------------------------------------------
-- Drop existing objects
--------------------------------------------------------------------------------

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE payment CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE invoice CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE rates CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

--------------------------------------------------------------------------------
-- INVOICE
--------------------------------------------------------------------------------

CREATE TABLE invoice (
    invoice_id      NUMBER GENERATED BY DEFAULT AS IDENTITY,
    invoice_date    DATE           NOT NULL,
    invoice_amount  NUMBER(18, 2)  NOT NULL,
    currency        VARCHAR2(3)    NOT NULL,

    CONSTRAINT pk_invoice
        PRIMARY KEY (invoice_id),

    CONSTRAINT chk_invoice_amount
        CHECK (invoice_amount >= 0),

    CONSTRAINT chk_invoice_currency
        CHECK (currency IN ('EUR', 'USD', 'SEK', 'GBP', 'JPY'))
);


--------------------------------------------------------------------------------
-- PAYMENT
--------------------------------------------------------------------------------

CREATE TABLE payment (
    payment_id      NUMBER GENERATED BY DEFAULT AS IDENTITY,
    payment_date    DATE           NOT NULL,
    payment_amount  NUMBER(18, 2)  NOT NULL,
    currency        VARCHAR2(3)    NOT NULL,
    invoice_id      NUMBER         NOT NULL,

    CONSTRAINT pk_payment
        PRIMARY KEY (payment_id),

    CONSTRAINT fk_payment_invoice
        FOREIGN KEY (invoice_id)
        REFERENCES invoice (invoice_id),

    CONSTRAINT chk_payment_amount
        CHECK (payment_amount > 0),

    CONSTRAINT chk_payment_currency
        CHECK (currency IN ('EUR', 'USD', 'SEK', 'GBP', 'JPY'))
);


--------------------------------------------------------------------------------
-- CURRENCY_RATE
--
-- ECB reference rate.
--
-- exchange_rate means:
--
--     1 EUR = exchange_rate units of currency
--
-- Examples:
--     EUR = 1
--     USD = 1.17000000
--     GBP = 0.86000000
--     JPY = 185.00000000
--
--------------------------------------------------------------------------------





CREATE TABLE rates (
    currency       VARCHAR2(3)   NOT NULL,
    rate_date      DATE          NOT NULL,
    exchange_rate  NUMBER(18, 8) NOT NULL,

    CONSTRAINT pk_rates
        PRIMARY KEY (currency, rate_date),

    CONSTRAINT chk_rates_currency
        CHECK (currency IN ('EUR', 'USD', 'SEK', 'GBP', 'JPY')),

    CONSTRAINT chk_rates_positive
        CHECK (exchange_rate > 0)
);

--------------------------------------------------------------------------------
-- Indexes
--------------------------------------------------------------------------------

CREATE INDEX idx_payment_invoice
    ON payment (invoice_id);

CREATE INDEX idx_payment_date
    ON payment (payment_date);

CREATE INDEX idx_rates_date
    ON rates (rate_date);
